# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.CharField(default=b'javascript:void(0)', max_length=100)),
                ('onclick', models.CharField(blank=True, default=b' ', max_length=100)),
                ('ruta_foto', models.ImageField(null=True, upload_to=b'menu_items/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuapp.MenuItem')),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'menuapp_menu_item',
            },
        ),
    ]
